### ISSUE TITLE
Character spawn lately.

### ISSUE THREAD

**Issue by Beginnervsro** [b0ykoe/ducksoup#12]
**Describe the bug**
Character spawn is late.

**To Reproduce**
I tried remove timermanager and CountdownManager spawn problem is fixed but get C10 not remove session.

**Filter (please complete the following information):**
 - OS: [e.g. Windows]

**Additional context**
I tried remove timermanager and CountdownManager spawn problem is fixed but get C10 not remove session.

**Comment by Beginnervsro** [comment]
???? why late spawn???

**Comment by b0ykoe** [comment]
Please post proper steps on how to reproduce. Post code examples and a video of the issue. Thank you.

**Comment by b0ykoe** [comment]
no answer was ever given, i label this as false report.
