### ISSUE TITLE
More info

### ISSUE THREAD

**Issue by S3eeD2** [b0ykoe/ducksoup#5]
Thanks for the great project, i think you need to add **[getting started]** , **[usage]** to readme (how to setup eveything).
No offense, but people can't just guess how it works, whos already knows this i dont think he really need it because he can make his own, a lot of information are missing on sro community specally for those whos trying to learn.

**Comment by b0ykoe** [comment]
This is not a finished, neither published, project. It is not intended to be used by a "casual" user. If you know how to set it up good. If you don't you can join the discord and ask proper questions to receive proper answers.

Once its in a state where I want to release it and I'll add a homepage with full documentation. I cannot give a ETA on that.
