### ISSUE TITLE
SharedObjects.AgentSessions

### ISSUE THREAD

**Issue by NewDivC** [b0ykoe/ducksoup#9]
**Describe the bug**
SharedObjects AgentSessions bug after char Exit/log out from game still keep the session 

**Expected behavior**
AgentSessions should  be automatically clean from terminated session 

**Screenshots**
/

**Filter (please complete the following information):**

**Additional context**

**Comment by b0ykoe** [comment]
What version of DuckSoup are you using? How did you test that the sessions are not removed? Is it a rare occurrence or does it happen everytime?

Thanks for your contribution to make DuckSoup better! :)

**Comment by xz013** [comment]
What version of DuckSoup are you using? 
1.8.4
How did you test that the sessions are not removed? 
 var ipCount = SharedObjects.AgentSessions.Count(Session => Session.ClientIp == session.ClientIp);
 IPlimit show me this problem when players out and can't get back 
 
 
 Is it a rare occurrence or does it happen everytime?
 every time 
 
 NOTE : when i test Exit  session cleaned but idk why all players after time get out and session still 
 may something wrong at remove session method or it get crashed 
 
 Have test this filter at my server with 60 players online

**Comment by xz013** [comment]
What version of DuckSoup are you using?
1.8.4
How did you test that the sessions are not removed?
var ipCount = SharedObjects.AgentSessions.Count(Session => Session.ClientIp == session.ClientIp);
IPlimit show me this problem when players out and can't get back

Is it a rare occurrence or does it happen everytime?
every time

NOTE : when i test Exit session cleaned but idk why all players after time get out and session still
may something wrong at remove session method or it get crashed

Have test this filter at my server with 60 players online

**Comment by xz013** [comment]
here is my report about this bug also

**Comment by NewDivC** [comment]
I believe the issue doesn't stem from the session itself, but rather from a client crash. I'm having difficulty comprehending this clearly. Could you please clarify whether the client crash has been resolved and the session removed?

**Comment by b0ykoe** [comment]
The filter has no "keep alive". If the server exceeds the keep alive ping it will close the session. Perhaps I'll add a keep alive ping on the 2.0 and close + remove the session once it exceeds.

**Comment by NewDivC** [comment]
"I would like to bring to your attention that there seem to be some issues with the Agent and Gateway circles. I believe it requires your attention for a closer examination." 
at my server : 
getaway : 387 session 
agent :142 
real online player at SMC :  48

**Comment by b0ykoe** [comment]
What version of DuckSoup are you using? How did you test that the sessions are not removed? Is it a rare occurrence or does it happen everytime?

**Comment by NewDivC** [comment]
I rigorously tested it on an actual server following your most recent update yesterday.
Upon careful examination of your feedback, I believe the issue may be rooted in the logic.
think better using concurrentdictionary  not list , it's back to Theard safety .
also it will be great if your session take id in one place not a class .

The problems seem to arise when a player enters and subsequently logs out, I conducted tests for approximately 4 hours yesterday to assess this situation.

**Comment by NewDivC** [comment]
method that displays the number of users at both the agent and gateway ,
several players are encountering issues with IP limits, primarily due to my implementation of IP checks within the agent sessions.

**Comment by b0ykoe** [comment]
I'll ask again. How did you test it? Send some code. Also if there is no version or code in the next comment from you I'll just close it and declare it as user failure.

The template is easy to understand, just fill it out, provide some context so I can test it. It isn't that hard.

**Comment by NewDivC** [comment]
private void  _updateTitleTimer(object? sender, ElapsedEventArgs e)
 {
     _updateTitleTimer.Stop();
     var s = $"G:  {SharedObjects.GatewaySessions.Count}    - A: {SharedObjects.AgentSessions.Count}";
 
     _updateTitleTimer.Start();
 }

 Version  1.8.4
 
 IP limit code : 
  var ipCount = SharedObjects.AgentSessions.Count(Session => Session.ClientIp == session.ClientIp);
    if (ipCount >= Library.SharedObjects.IPLimit)
  {
    
      var chars = SharedObjects.AgentSessions.Where(Session => Session.ClientIp == session.ClientIp);
      var dat = chars.Select(s => s.SessionData.Charname).ToList();
      //await Console.Out.WriteLineAsync($"Count ip : {ipCount} , ip is :{session.ClientIp}");
      //foreach (var item in dat)
      //{
      //    await Console.Out.WriteLineAsync(item);
      //}
      Packet ipLimit = new Packet(0xA102);
      ipLimit.WriteUInt8(0x03);
      ipLimit.WriteUInt8(0x08);
      await session.SendToClient(ipLimit);

     
      return new PacketResult(PacketResultType.Block);
  }

**Comment by b0ykoe** [comment]
Please try out the latest push.

**Comment by NewDivC** [comment]
result after 6 hour test : 
https://prnt.sc/cr9OqTkixhEb
it wroks so good at first 5 hour but smth wrong happen here make result very bad : 
full report : https://notes.xxi2.com/zuir5o

**Comment by NewDivC** [comment]
any news ?

**Comment by b0ykoe** [comment]
Should be fixed in #devel
